In [1]:
import pandas as pd

In [2]:
import matplotlib as plt

In [3]:
getdatawithheader1 = pd.read_csv('pandadatarecthis.csv', skiprows=[0,1,2,3], index_col = 3, header = 0)

In [4]:
getdatawithheader1

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
042735BC3,abca,1234a,Outstanding,ARROW ELECTRONICS INC20230301,NaN,19999,20008,-9,NaN,103.67,...,0,0,0,0,0,0,0,0,0,NaN
717081103,abcd,1234g,Outstanding,PFIZER INC,NaN,399,455,-56,NaN,40.61,...,0,0,0,0,0,0,0,0,0,NaN
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN
03523TBP2,efgw,4567b,Outstanding,ANHEUSER-BUSCH INBEV WOR20220715,NaN,19999,20000,-1,NaN,98.89,...,0,0,0,0,0,0,0,0,0,NaN

In [5]:
barplot = getdatawithheader[['Qty Loomis','Qty Bank','Qty Var']]

NameError: name 'getdatawithheader' is not defined

In [6]:
barplot = getdatawithheader1['Qty Loomis','Qty Bank','Qty Var']

KeyError: ('Qty Loomis', 'Qty Bank', 'Qty Var')

In [7]:
barplot = getdatawithheader1[['Qty Loomis','Qty Bank','Qty Var']]

In [8]:
barplot

           Qty Loomis  Qty Bank  Qty Var
Security
042735BC3       19999     20008       -9
717081103         399       455      -56
92826C839         199       600     -401
02079K107         509     99988   -99479
31162100          996       779      217
03523TBP2       19999     20000       -1

In [9]:
qtyvar =  getdatawithheader1['Qty Var'] > abs(100)

In [10]:
qtyvar =  getdatawithheader1['Qty Var'] > abs(1001)

In [11]:
qtyvar

Security
042735BC3    False
717081103    False
92826C839    False
02079K107    False
31162100     False
03523TBP2    False
Name: Qty Var, dtype: bool

In [12]:
qtyvar1 =  getdatawithheader1['Qty Var'] > 100

In [13]:
qtyvar2 =  getdatawithheader1['Qty Var'] < 1000

In [14]:
var = [qtyvar1 | qtyvar2]

In [15]:
var

[Security
 042735BC3    True
 717081103    True
 92826C839    True
 02079K107    True
 31162100     True
 03523TBP2    True
 Name: Qty Var, dtype: bool]

In [16]:
qty = getdatawithheader['Qty Var'] > 1000
bank = getdatawithheader['Qty Bank'] > 2000
getdatawithheader[qty]

NameError: name 'getdatawithheader' is not defined

In [17]:
qty = getdatawithheader1['Qty Var'] > 1000
bank = getdatawithheader1['Qty Bank'] > 2000
getdatawithheader[qty]

NameError: name 'getdatawithheader' is not defined

In [18]:
qty = getdatawithheader1['Qty Var'] > 1000
bank = getdatawithheader1['Qty Bank'] > 2000
getdatawithheader1[qty]

Empty DataFrame
Columns: [Loomis_Account_Name,  Bank Account, Break Type-Separate Accounts, Description, Local Curr, Qty Loomis, Qty Bank, Qty Var, Local Prc Loomis,   Local Prc Bank , Prc Var (%), Base MV Loomis, Base MV Bank, MV Var, MV Var(%), Base Cost Loomis, Base Cost  Bank, Cost Var, Base Accr Loomis, Base Accr Bank, Accr Var (%), Basis_Pt (%), Comment]
Index: []

[0 rows x 23 columns]

In [19]:
qty = getdatawithheader1['Qty Var'] < 1000
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
042735BC3,abca,1234a,Outstanding,ARROW ELECTRONICS INC20230301,NaN,19999,20008,-9,NaN,103.67,...,0,0,0,0,0,0,0,0,0,NaN
717081103,abcd,1234g,Outstanding,PFIZER INC,NaN,399,455,-56,NaN,40.61,...,0,0,0,0,0,0,0,0,0,NaN
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN
03523TBP2,efgw,4567b,Outstanding,ANHEUSER-BUSCH INBEV WOR20220715,NaN,19999,20000,-1,NaN,98.89,...,0,0,0,0,0,0,0,0,0,NaN

In [20]:
qty = getdatawithheader1['Qty Var'] < -1000
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN

In [21]:
qty = getdatawithheader1['Qty Var'] < abs(200)
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
042735BC3,abca,1234a,Outstanding,ARROW ELECTRONICS INC20230301,NaN,19999,20008,-9,NaN,103.67,...,0,0,0,0,0,0,0,0,0,NaN
717081103,abcd,1234g,Outstanding,PFIZER INC,NaN,399,455,-56,NaN,40.61,...,0,0,0,0,0,0,0,0,0,NaN
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
03523TBP2,efgw,4567b,Outstanding,ANHEUSER-BUSCH INBEV WOR20220715,NaN,19999,20000,-1,NaN,98.89,...,0,0,0,0,0,0,0,0,0,NaN

In [22]:
qty = getdatawithheader1['Qty Var'] < abs(400)
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
042735BC3,abca,1234a,Outstanding,ARROW ELECTRONICS INC20230301,NaN,19999,20008,-9,NaN,103.67,...,0,0,0,0,0,0,0,0,0,NaN
717081103,abcd,1234g,Outstanding,PFIZER INC,NaN,399,455,-56,NaN,40.61,...,0,0,0,0,0,0,0,0,0,NaN
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN
03523TBP2,efgw,4567b,Outstanding,ANHEUSER-BUSCH INBEV WOR20220715,NaN,19999,20000,-1,NaN,98.89,...,0,0,0,0,0,0,0,0,0,NaN

In [23]:
qty = getdatawithheader1['Qty Var'] > abs(400)
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

Empty DataFrame
Columns: [Loomis_Account_Name,  Bank Account, Break Type-Separate Accounts, Description, Local Curr, Qty Loomis, Qty Bank, Qty Var, Local Prc Loomis,   Local Prc Bank , Prc Var (%), Base MV Loomis, Base MV Bank, MV Var, MV Var(%), Base Cost Loomis, Base Cost  Bank, Cost Var, Base Accr Loomis, Base Accr Bank, Accr Var (%), Basis_Pt (%), Comment]
Index: []

[0 rows x 23 columns]

In [24]:
qty = getdatawithheader1['Qty Var'] > abs(200)
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN

In [25]:
qty = getdatawithheader1['Qty Var'] > 200 | < 200 
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty]

SyntaxError: invalid syntax (<ipython-input-25-a1a86ebfdf8f>, line 1)

In [26]:
qty = getdatawithheader1['Qty Var'] < -20
qty2 = getdatawithheader1['Qty Var'] > 200
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty, qty2  ]

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [27]:
qty = getdatawithheader1['Qty Var'] < -20
qty2 = getdatawithheader1['Qty Var'] > 200
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty | qty2  ]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
717081103,abcd,1234g,Outstanding,PFIZER INC,NaN,399,455,-56,NaN,40.61,...,0,0,0,0,0,0,0,0,0,NaN
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN

In [28]:
qty = getdatawithheader1['Qty Var'] < -200
qty2 = getdatawithheader1['Qty Var'] > 200
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty | qty2  ]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN

In [29]:
qty = getdatawithheader1['Qty Var'] < -200
qty2 = getdatawithheader1['Qty Var'] > 200
bank = getdatawithheader1['Qty Bank'] > 200
getdatawithheader1[qty | qty2 | bank ]

,Loomis_Account_Name,Bank Account,Break Type-Separate Accounts,Description,Local Curr,Qty Loomis,Qty Bank,Qty Var,Local Prc Loomis,Local Prc Bank,...,MV Var,MV Var(%),Base Cost Loomis,Base Cost Bank,Cost Var,Base Accr Loomis,Base Accr Bank,Accr Var (%),Basis_Pt (%),Comment
Security,,,,,,,,,,,,,,,,,,,,,
042735BC3,abca,1234a,Outstanding,ARROW ELECTRONICS INC20230301,NaN,19999,20008,-9,NaN,103.67,...,0,0,0,0,0,0,0,0,0,NaN
717081103,abcd,1234g,Outstanding,PFIZER INC,NaN,399,455,-56,NaN,40.61,...,0,0,0,0,0,0,0,0,0,NaN
92826C839,abce,1234a,Outstanding,VISA INC-CLASS A SHRS,NaN,199,600,-401,NaN,164.43,...,0,0,0,0,0,0,0,0,0,NaN
02079K107,efgi,4567y,Outstanding,ALPHABET INC-CL C,NaN,509,99988,-99479,NaN,1188.48,...,0,0,0,0,0,0,0,0,0,NaN
31162100,efgr,4567f,Outstanding,AMGEN INC,NaN,996,779,217,NaN,179.32,...,0,0,0,0,0,0,0,0,0,NaN
03523TBP2,efgw,4567b,Outstanding,ANHEUSER-BUSCH INBEV WOR20220715,NaN,19999,20000,-1,NaN,98.89,...,0,0,0,0,0,0,0,0,0,NaN

In [30]:
qtyr = 'Qty Var'
bankr = 'Qty Bank'

In [31]:
getdatawithheader1[[qtyr,bankr]]

           Qty Var  Qty Bank
Security
042735BC3       -9     20008
717081103      -56       455
92826C839     -401       600
02079K107   -99479     99988
31162100       217       779
03523TBP2       -1     20000

In [32]:
%matplotlib notebook

In [33]:
matplot = getdatawithheader1[[qtyr,bankr]]

In [34]:
matplot.bar

AttributeError: 'DataFrame' object has no attribute 'bar'

In [35]:
matplot.plot.bar

In [36]:
matplot.plot.bar()